<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNyx3yo9\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNyx3yo9/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerNyx3yo9.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerNyx3yo9\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerNyx3yo9\appProdProjectContainer([
    'container.build_hash' => 'Nyx3yo9',
    'container.build_id' => 'b12e8d66',
    'container.build_time' => 1588293197,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNyx3yo9');
