<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBbl0taj\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBbl0taj/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerBbl0taj.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerBbl0taj\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerBbl0taj\appDevDebugProjectContainer([
    'container.build_hash' => 'Bbl0taj',
    'container.build_id' => 'c43673d1',
    'container.build_time' => 1600365030,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBbl0taj');
