<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'AppBundle\Form\roleType' shared autowired service.

return $this->services['AppBundle\\Form\\roleType'] = new \AppBundle\Form\roleType();
